### ISSUE TITLE
Markdown format mode stopped doing anything

### ISSUE THREAD

**Issue by Morozzs** [pc035860/yt-timetag#58]
I used to export timestamps with youtube links via markdown mode (export the text -> markdown format), but now all of a sudden it doesn't change anything. 
Tested with Vivaldi and Firefox. Happened on 29.05.2024

EDIT: Actually, it does work, it just looks like this, but if I choose the copy option then it copies properly with timestamps.

![testest](https://github.com/pc035860/yt-timetag/assets/31186716/e1c8f917-f9d0-451d-a930-7197f6433af3)

**Comment by pc035860** [comment]
This is a bug that was introduced in version 1.6.0. A new version will be released today. Thank you for your report!

**Comment by pc035860** [comment]
Close via 105a1d08fd1f85b34784eace56987eba540a7ebb
